In [1]:
import numpy as np

In [2]:
a1= np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[123,23],[222,232]])
a2

array([[123,  23],
       [222, 232]])

In [7]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 2)

In [11]:
a3.shape

(3, 2, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.size, a2.size, a3.size

(3, 4, 18)

In [14]:
import pandas as pd

In [15]:
df = pd.DataFrame(a2)

In [16]:
df

0    1
0  123   23
1  222  232

In [17]:
df = pd.DataFrame(a3)

ValueError: Must pass 2-d input. shape=(3, 2, 3)

In [ ]:
df

In [18]:
sample_arr = np.array([1,2,3])

In [19]:
sample_arr

array([1, 2, 3])

In [20]:
ones = np.ones((2,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
zeros = np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0,10,2)

In [25]:
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0,10,size=(3,5))

In [27]:
random_array

array([[4, 2, 4, 0, 7],
       [9, 1, 8, 0, 8],
       [3, 7, 6, 1, 4]], dtype=int32)

In [30]:
np.random.random((5,3))

array([[0.65621229, 0.90205289, 0.93048627],
       [0.77102804, 0.59173413, 0.01248162],
       [0.40347279, 0.9371114 , 0.98828378],
       [0.54068779, 0.2171239 , 0.71496065],
       [0.30366941, 0.507985  , 0.05379434]])

In [31]:
np.random.seed()

In [37]:
np.random.seed(seed=0)
random_array2 = np.random.randint(0,10,size=(3,5))
random_array2

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]], dtype=int32)

In [38]:
np.unique(random_array2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [39]:
a1

array([1, 2, 3])

In [40]:
a2

array([[123,  23],
       [222, 232]])

In [41]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [42]:
a1[0]

np.int64(1)

In [43]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
a1+ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [45]:
a1

array([1, 2, 3])

In [46]:
a1*a2

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [47]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,2) (3,2,3) 

In [48]:
new_arr = a2.reshape(2,3)

ValueError: cannot reshape array of size 4 into shape (2,3)

In [49]:
a2

array([[123,  23],
       [222, 232]])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [54]:
new_arr = np.array(
    [[1,  1,1],
       [2,2,2],[3,3,3]]
)

In [56]:
a1*new_arr

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [57]:
new_arr * a3

ValueError: operands could not be broadcast together with shapes (3,3) (3,2,3) 

In [58]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [60]:
reshaped_arr = a3.reshape(3, 1,3)

ValueError: cannot reshape array of size 18 into shape (3,1,3)

In [61]:
arr1 = np.ones((3, 3))  

In [62]:
arr2 = np.ones((3, 2, 3))

In [63]:
arr1*arr2

ValueError: operands could not be broadcast together with shapes (3,3) (3,2,3) 

In [64]:
arr1_reshaped = arr1.reshape(3, 1, 3)

In [65]:
arr1_reshaped *arr2

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [66]:
arr1_reshaped

array([[[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]]])

In [67]:
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
np.random.seed(0)

In [69]:
mat1=np.random.randint(10, size=(5,3))
mat2=np.random.randint(10, size=(5,3))

In [70]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [71]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [72]:
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [73]:
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [74]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]], dtype=int32)

In [75]:
mat1.T.shape

(3, 5)

In [76]:
mat3 = np.dot(mat1,mat2.T)

In [77]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [78]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [80]:
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon","Tues","Wed","Thurs","Fri"],
                            columns=["Almond Butter","Peanut butter", "Cashew butter"])

In [81]:
weekly_sales

Almond Butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [82]:
prices = np.array([10,8,12])

In [85]:
butter_prices = pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["Almond Butter","Peanut butter", "Cashew butter"])

In [86]:
butter_prices

Almond Butter  Peanut butter  Cashew butter
Price             10              8             12

In [87]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [89]:
total_sales = prices.dot(sales_amounts.T)

In [90]:
total_sales

array([240, 138, 458, 232, 142])

In [91]:
butter_prices

Almond Butter  Peanut butter  Cashew butter
Price             10              8             12

In [92]:
weekly_sales

Almond Butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [93]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [94]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [96]:
weekly_sales["Total ($)"] = daily_sales.T

In [97]:
weekly_sales

Almond Butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

<img src="numpy-images/panda.png" />

In [101]:
from matplotlib.image import imread

In [102]:
panda = imread("numpy-images/panda.png")

In [103]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [104]:
panda.size, panda.shape

(24465000, (2330, 3500, 3))

<img src="numpy-images/car-photo.png" />